name: Slack Notice Action
description: A GitHub Action to notify slack.
author: sonots
inputs:
  status:
    description: Specify success or failure or cancelled or custom.
  payload:
    description: |
      json payload
      refs https://github.com/slackapi/node-slack-sdk/blob/v5.0.0/packages/webhook/src/IncomingWebhook.ts#L91-L106)
  mention:
    description: |
      Specify channel or here or `user_id`.
      refs: https://api.slack.com/reference/surfaces/formatting#mentioning-users
    default: ''
  only_mention_fail:
    description: |
      Specify channel or here or `user_id`.
      refs: https://api.slack.com/reference/surfaces/formatting#mentioning-users
    default: ''
  title:
    description: Title for slack notification.
    default: ''
  text:
    description: You can overwrite text.
    default: ''
runs:
  using: node24
  main: dist/index.js
branding:
  icon: bell
  color: blue
