name: Slack Pre
on:
  push:
    branches:
      - pre

jobs:
  notification:
    runs-on: ubuntu-latest
    steps:
      - name: Succeeded Check
        uses: sonots/slack-notice-action@pre
        with:
          status: Success
          text_on_success: ':white_check_mark: text_on_success — visible on success'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_FOR_INTEGRATION_TEST }}
      - name: Failed Check
        uses: sonots/slack-notice-action@pre
        with:
          status: Failure
          only_mention_fail: here
          text_on_fail: ':rotating_light: text_on_fail — visible on failure'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_FOR_INTEGRATION_TEST }}
      - name: Canceled Check
        uses: sonots/slack-notice-action@pre
        with:
          status: Cancelled
          text_on_cancel: ':warning: text_on_cancel — visible on cancellation'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_FOR_INTEGRATION_TEST }}
      - name: Custom Field Check
        uses: sonots/slack-notice-action@pre
        with:
          status: custom
          payload: |
            {
              text: "Custom Field Check",
              attachments: [{
                "author_name": "sonots@slack-notice-action", // json
                fallback: 'fallback',
                color: 'good',
                title: 'CI Result',
                text: 'Succeeded',
                fields: [{
                  title: 'lower case',
                  value: 'LOWER CASE CHECK'.toLowerCase(),
                  short: true
                },
                {
                  title: 'reverse',
                  value: 'gnirts esrever'.split('').reverse().join(''),
                  short: true
                },
                {
                  title: 'long title1',
                  value: 'long value1',
                  short: false
                }],
                actions: [{
                }]
              }]
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_FOR_INTEGRATION_TEST }}
      - name: Check
        uses: sonots/slack-notice-action@pre
        with:
          status: ${{ job.status }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
