name: Check for uncommitted changes
on:
  push:
    branches:
      - pre
      - main
      - 'v*'

jobs:
  uncommitted:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - run: npm ci
      - run: npm run release
      - name: check for uncommitted changes
        run: |
          git diff --exit-code -- . ':!node_modules' \
          || (echo "##[error] found changed files after build. please 'npm run build && npm run format'" \
                   "and check in all changes" \
              && exit 1)
